
const text = [
  '  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer pulvinar sem ex, in condimentum nisi cursus vitae. Pellentesque ac eros orci. Curabitur fermentum fringilla ex, finibus interdum mi ultricies in. Interdum et malesuada fames ac ante ipsum primis in faucibus. Etiam sit amet commodo lorem. Donec fermentum ligula libero, interdum volutpat libero finibus et. Sed non dolor libero. Ut sagittis sem vel aliquet viverra. Fusce elit neque, maximus sed quam id, finibus tempus odio. Etiam eu consectetur sem. Maecenas congue dignissim ligula, et tincidunt dolor porttitor sed. Curabitur hendrerit augue vel risus tempor, sed viverra tortor viverra.',
  'In orci turpis, malesuada nec consequat in, malesuada ut nisl. Curabitur mollis nunc id leo finibus varius. Mauris ultricies ante quis sapien suscipit vestibulum at nec nisi. Maecenas sed tellus elit. Nunc id est eu quam tempus dictum. Quisque augue nisi, bibendum in nulla nec, semper egestas mauris. Vestibulum ac velit id urna vestibulum posuere. Nulla facilisi. Aenean et sodales purus. Suspendisse dapibus semper egestas. Mauris et tellus rhoncus libero eleifend fermentum.',
  'In vestibulum, nisl sit amet accumsan pellentesque, mi ipsum finibus velit, eu semper turpis odio a ante. Fusce venenatis velit at ex luctus, sit amet volutpat est sagittis. Nam mi libero, iaculis sit amet molestie quis, lobortis sit amet ex. Donec et tristique arcu. Nullam suscipit pulvinar nisi vitae condimentum. Pellentesque malesuada justo ut vulputate fringilla. Phasellus dictum, massa quis congue vehicula, quam neque aliquet est, id pulvinar arcu urna at dui.',
  'Quisque sed turpis quis enim volutpat dignissim vitae eu lorem. Praesent eu odio aliquet, vestibulum sapien non, ultrices nisl. In condimentum dui erat, in malesuada nisi sodales sed. Interdum et malesuada fames ac ante ipsum primis in faucibus. Ut ut interdum diam. Quisque at leo sed nisl facilisis pellentesque a in urna. Donec id quam nec quam fringilla ultrices non egestas tortor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec aliquam sodales urna id molestie. Nulla euismod neque eu velit volutpat dapibus. Praesent elementum dapibus dui. Phasellus ut erat dolor.',
  'Cras malesuada eu diam id dignissim. Integer convallis consequat scelerisque. Aenean at dui at eros bibendum hendrerit. Vestibulum gravida ipsum sit amet tortor gravida faucibus. Duis pellentesque eros rutrum nisl fringilla venenatis. Etiam ut blandit augue. In sed dolor sit amet urna bibendum pellentesque. Nam eleifend ut est vitae suscipit. Donec lacinia non velit id fermentum. Nullam et neque non libero malesuada auctor sed vel massa.',
  'httpsNullam lobortis tincidunt pulvinar. Pellentesque efficitur magna et elit finibus, nec blandit nisi rutrum. Maecenas vitae ipsum metus. Integer congue tellus et leo mattis cursus. Curabitur et est et eros congue finibus efficitur ut tellus. Duis condimentum tellus eu metus pretium dictum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed ac augue iaculis, bibendum ipsum et, ultrices nibh. Pellentesque sit amet nunc ipsum. Proin vel tellus dapibus, tempus nulla imperdiet, feugiat libero. Aliquam sed nisl eget ipsum ultricies elementum. Phasellus lacinia maximus mauris non pellentesque. Aenean lectus neque, iaculis nec lectus ut, pellentesque feugiat erat. Aliquam hendrerit felis id lacus egestas fermentum. Morbi pellentesque neque ut arcu malesuada tempus. Curabitur volutpat gravida felis ac semper.',
  'Etiam placerat suscipit enim, nec finibus nibh laoreet non. Etiam odio nisl, pharetra a egestas non, hendrerit eget ligula. Mauris sed arcu quis tellus pharetra molestie sed sit amet dui. Nunc felis enim, fermentum vitae elementum egestas, blandit quis sem. Vivamus orci leo, blandit vel finibus quis, tincidunt at metus. Cras nec lobortis sapien. Vivamus eu nunc arcu. Curabitur malesuada arcu ac quam blandit, at bibendum elit aliquam. Pellentesque sed mi sapien. Aliquam imperdiet sem eu nisl faucibus, vel aliquet purus facilisis.',
  'Duis bibendum erat auctor odio hendrerit, quis eleifend lectus elementum. Phasellus porta vulputate metus, eu tincidunt diam molestie quis. Sed non felis lorem. Vivamus vel purus et sem blandit scelerisque. Integer vehicula lacinia convallis. Cras aliquam ullamcorper lacus quis malesuada. Maecenas elementum non ligula quis tristique.',
  'Cras at consectetur elit, sed laoreet lectus. Sed aliquet interdum laoreet. Phasellus non auctor nulla, non tristique orci. Duis mattis porttitor nulla vitae condimentum. Suspendisse potenti. Suspendisse sed tempor diam, vitae scelerisque leo. Nam nec mollis urna. Cras lobortis neque elit. Nullam id erat dignissim, maximus felis id, faucibus sapien. Vivamus vitae ante magna. Integer iaculis quam id ligula porttitor gravida. Nulla mollis, est nec consectetur placerat, nisl dolor sodales ex, in cursus velit arcu nec libero. Proin nec erat in tortor pharetra laoreet. Maecenas sed lorem bibendum, porta quam vel, vestibulum nibh.',
  'Pellentesque sollicitudin mauris lorem, ac pellentesque lectus semper non. Phasellus placerat ligula eget justo feugiat aliquam. Donec scelerisque velit vitae felis elementum eleifend. Vivamus quis turpis eget odio suscipit feugiat at vel arcu. Nunc quis varius lorem, at consectetur turpis. Donec tincidunt pretium mattis. Sed sed diam gravida, tempus orci vitae, imperdiet tortor. Quisque quis blandit purus. Vestibulum tristique dui id nunc feugiat, quis cursus ligula rutrum. Sed tincidunt maximus gravida. Duis consectetur faucibus diam, hendrerit fermentum nibh mattis eu.',
  'Duis et erat congue, interdum velit id, vulputate lectus. Mauris sem justo, facilisis id ullamcorper in, viverra vel nulla. Sed varius, felis non tempor placerat, lorem neque iaculis mauris, id mollis ante tortor vel neque. Nunc tempus arcu quis leo placerat rutrum. Fusce eu augue ligula. Donec eu nisl ut ex dapibus gravida. Phasellus eu fermentum ipsum, sit amet tincidunt nisi. Duis pellentesque vehicula lectus ut consequat. Phasellus elementum posuere pellentesque. Maecenas lorem elit, pulvinar non convallis et, condimentum quis metus.',
  'Suspendisse fringilla tellus quis eros imperdiet tincidunt. Vivamus vel mollis nisi, sed iaculis sapien. Quisque porta mauris eget ante porttitor vehicula. Proin sollicitudin semper erat, ut accumsan orci egestas id. Donec non suscipit augue. Cras sed semper tortor. Donec nec metus porta, vehicula magna vel, ultrices ex. Maecenas vel dapibus leo. Donec lorem lorem, scelerisque sit amet laoreet sed, commodo vel risus. Vivamus accumsan lorem ac risus blandit mattis. Cras ultrices eros leo, at ultricies sapien elementum ac. Aenean erat massa, eleifend non lacus id, rhoncus volutpat diam.',
  'Fusce tempus quam eu sagittis porttitor. Donec sit amet urna aliquet, placerat erat ac, pellentesque tellus. Cras pharetra ultricies accumsan. Sed nec felis eget leo fringilla lacinia eu sed tortor. Morbi congue tincidunt turpis ac faucibus. Nulla accumsan lacinia bibendum. Curabitur suscipit ipsum ut enim bibendum, vel lacinia tortor luctus. Praesent consequat tellus nec lorem consectetur, eu congue mauris hendrerit. Curabitur ultrices arcu volutpat, interdum lorem eu, consequat sem. Sed nec enim interdum, tincidunt dolor non, varius odio. Morbi rhoncus ipsum at iaculis rutrum.',
  'Curabitur consectetur lorem eget nunc tempus hendrerit. Pellentesque fringilla, arcu quis tincidunt imperdiet, velit nunc tincidunt nisl, eget pellentesque neque dui sed elit. Phasellus in magna aliquet, placerat est sed, pharetra dui. Nam eu tincidunt lorem, eu lobortis mi. Nulla ut ex vitae lectus ultricies imperdiet. Etiam ultricies nisl et dignissim sodales. Proin cursus turpis ac pretium maximus. Aenean nec sem imperdiet, porta urna congue, auctor elit. Nullam nunc risus, pretium accumsan massa eu, blandit tempor metus. Nullam at libero lorem. Sed rutrum ut justo vitae dignissim.',
  'Maecenas ut vulputate mauris, ut finibus arcu. Nulla et ullamcorper orci. Morbi varius, neque at elementum euismod, risus velit varius tortor, sagittis luctus neque arcu sit amet lectus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Aenean ante mauris, euismod finibus varius convallis, congue vitae sem. Vestibulum volutpat condimentum dui, congue semper sapien dignissim a. Donec efficitur ligula eget turpis lacinia lacinia. Interdum et malesuada fames ac ante ipsum primis in faucibus.',
  'Nam porta gravida ante non pulvinar. Interdum et malesuada fames ac ante ipsum primis in faucibus. Proin cursus tincidunt sapien, vitae tincidunt nisi maximus a. Aliquam interdum, eros nec egestas cursus, justo urna pulvinar velit, ut eleifend nisi dolor id orci. Suspendisse nec magna eget lorem bibendum consectetur ut quis odio. Mauris sit amet nunc lacus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Praesent ac nulla non augue fringilla pretium. Suspendisse eu turpis molestie urna cursus ultricies condimentum id massa. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam porttitor metus ut mi gravida, eget lacinia nunc dignissim. Curabitur lobortis mi eget erat posuere, sed commodo eros scelerisque. Donec id lorem aliquam elit aliquet eleifend vitae ullamcorper mauris.',
  'Sed tempus purus eros. Cras nisi elit, elementum at massa eget, vehicula sodales ante. Duis vehicula neque porta magna faucibus, ac tempus dolor hendrerit. Nulla nec semper metus. Praesent lectus neque, auctor ut sapien id, consectetur efficitur eros. Ut egestas, mi a facilisis dapibus, leo erat sodales ligula, vitae consectetur odio metus eget risus. Nullam id tincidunt lorem, ut aliquam lacus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam aliquet mauris vitae tempus bibendum. Phasellus massa mi, dictum ut justo sed, accumsan cursus orci. Praesent at felis hendrerit, convallis diam ac, vestibulum dolor. Aenean eget augue nulla. Praesent congue interdum aliquam.',
  'Aliquam tellus lacus, venenatis interdum rutrum ut, tincidunt vitae eros. Integer aliquam, mi non lobortis efficitur, neque purus sagittis nulla, ac ornare arcu justo id justo. Morbi egestas urna nec leo consequat pulvinar. Sed sollicitudin dui magna, faucibus pharetra odio tincidunt ut. Nam consectetur, purus nec congue venenatis, felis lectus pulvinar urna, a blandit tellus ex sit amet neque. Fusce ornare tincidunt massa, quis hendrerit erat interdum quis. Suspendisse a mi augue. Cras vitae lacus in erat fermentum bibendum vel eu orci. Morbi a est ac velit tincidunt bibendum a eget neque. Curabitur lacus ex, dignissim tincidunt arcu eget, tincidunt feugiat magna. Praesent eleifend, quam ut rutrum volutpat, dui diam dictum eros, eu eleifend velit sapien vel sapien. Vestibulum pellentesque urna mattis faucibus mattis. Suspendisse orci sem, molestie sit amet felis a, semper accumsan mi. Pellentesque pretium est ante, quis convallis quam efficitur vel.',
  'Ut porttitor odio at nunc mollis molestie. Aliquam tortor lorem, gravida in vehicula et, ornare sed augue. Donec vitae imperdiet elit. Nulla finibus fermentum tincidunt. In imperdiet gravida scelerisque. Proin eget ipsum ac felis sodales molestie vitae tristique orci. Morbi nec velit cursus, accumsan ante at, ullamcorper dolor. Donec dignissim, nibh blandit euismod fermentum, dolor augue efficitur felis, feugiat auctor quam nisi eget lectus. Cras est leo, auctor eu odio vitae, finibus cursus dui. Nunc iaculis sollicitudin dapibus. Proin elementum elementum erat, a blandit lacus cursus hendrerit. Mauris lacinia sollicitudin dui, nec auctor dolor volutpat at. Sed in mi massa. Suspendisse convallis diam at lacus tincidunt efficitur. Morbi tincidunt sed libero sit amet rhoncus. Vivamus dapibus eros tellus, nec laoreet leo molestie in.'
];

export default text;
